// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/portdomain/v1/port_domain_api.proto

package portdomain_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	Locode               string         `protobuf:"bytes,1,opt,name=locode,proto3" json:"locode,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string         `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string         `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string       `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string       `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          *latlng.LatLng `protobuf:"bytes,7,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string         `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string         `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string       `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	ForeignCode          int32          `protobuf:"varint,11,opt,name=foreign_code,json=foreignCode,proto3" json:"foreign_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetLocode() string {
	if m != nil {
		return m.Locode
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() *latlng.LatLng {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetForeignCode() int32 {
	if m != nil {
		return m.ForeignCode
	}
	return 0
}

type UpsertPortRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertPortRequest) Reset()         { *m = UpsertPortRequest{} }
func (m *UpsertPortRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertPortRequest) ProtoMessage()    {}
func (*UpsertPortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{1}
}

func (m *UpsertPortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertPortRequest.Unmarshal(m, b)
}
func (m *UpsertPortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertPortRequest.Marshal(b, m, deterministic)
}
func (m *UpsertPortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertPortRequest.Merge(m, src)
}
func (m *UpsertPortRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertPortRequest.Size(m)
}
func (m *UpsertPortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertPortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertPortRequest proto.InternalMessageInfo

type UpsertPortResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertPortResponse) Reset()         { *m = UpsertPortResponse{} }
func (m *UpsertPortResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertPortResponse) ProtoMessage()    {}
func (*UpsertPortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{2}
}

func (m *UpsertPortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertPortResponse.Unmarshal(m, b)
}
func (m *UpsertPortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertPortResponse.Marshal(b, m, deterministic)
}
func (m *UpsertPortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertPortResponse.Merge(m, src)
}
func (m *UpsertPortResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertPortResponse.Size(m)
}
func (m *UpsertPortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertPortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertPortResponse proto.InternalMessageInfo

type GetPortInfoByCodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortInfoByCodeRequest) Reset()         { *m = GetPortInfoByCodeRequest{} }
func (m *GetPortInfoByCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetPortInfoByCodeRequest) ProtoMessage()    {}
func (*GetPortInfoByCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{3}
}

func (m *GetPortInfoByCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortInfoByCodeRequest.Unmarshal(m, b)
}
func (m *GetPortInfoByCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortInfoByCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetPortInfoByCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortInfoByCodeRequest.Merge(m, src)
}
func (m *GetPortInfoByCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetPortInfoByCodeRequest.Size(m)
}
func (m *GetPortInfoByCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortInfoByCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortInfoByCodeRequest proto.InternalMessageInfo

type GetPortInfoByCodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortInfoByCodeResponse) Reset()         { *m = GetPortInfoByCodeResponse{} }
func (m *GetPortInfoByCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetPortInfoByCodeResponse) ProtoMessage()    {}
func (*GetPortInfoByCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{4}
}

func (m *GetPortInfoByCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortInfoByCodeResponse.Unmarshal(m, b)
}
func (m *GetPortInfoByCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortInfoByCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetPortInfoByCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortInfoByCodeResponse.Merge(m, src)
}
func (m *GetPortInfoByCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetPortInfoByCodeResponse.Size(m)
}
func (m *GetPortInfoByCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortInfoByCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortInfoByCodeResponse proto.InternalMessageInfo

type GetPortInfoByCodeBatchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortInfoByCodeBatchRequest) Reset()         { *m = GetPortInfoByCodeBatchRequest{} }
func (m *GetPortInfoByCodeBatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetPortInfoByCodeBatchRequest) ProtoMessage()    {}
func (*GetPortInfoByCodeBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{5}
}

func (m *GetPortInfoByCodeBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortInfoByCodeBatchRequest.Unmarshal(m, b)
}
func (m *GetPortInfoByCodeBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortInfoByCodeBatchRequest.Marshal(b, m, deterministic)
}
func (m *GetPortInfoByCodeBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortInfoByCodeBatchRequest.Merge(m, src)
}
func (m *GetPortInfoByCodeBatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetPortInfoByCodeBatchRequest.Size(m)
}
func (m *GetPortInfoByCodeBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortInfoByCodeBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortInfoByCodeBatchRequest proto.InternalMessageInfo

type GetPortInfoByCodeBatchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortInfoByCodeBatchResponse) Reset()         { *m = GetPortInfoByCodeBatchResponse{} }
func (m *GetPortInfoByCodeBatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetPortInfoByCodeBatchResponse) ProtoMessage()    {}
func (*GetPortInfoByCodeBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b0cf120d2396f8, []int{6}
}

func (m *GetPortInfoByCodeBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortInfoByCodeBatchResponse.Unmarshal(m, b)
}
func (m *GetPortInfoByCodeBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortInfoByCodeBatchResponse.Marshal(b, m, deterministic)
}
func (m *GetPortInfoByCodeBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortInfoByCodeBatchResponse.Merge(m, src)
}
func (m *GetPortInfoByCodeBatchResponse) XXX_Size() int {
	return xxx_messageInfo_GetPortInfoByCodeBatchResponse.Size(m)
}
func (m *GetPortInfoByCodeBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortInfoByCodeBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortInfoByCodeBatchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Port)(nil), "portdomain.v1.Port")
	proto.RegisterType((*UpsertPortRequest)(nil), "portdomain.v1.UpsertPortRequest")
	proto.RegisterType((*UpsertPortResponse)(nil), "portdomain.v1.UpsertPortResponse")
	proto.RegisterType((*GetPortInfoByCodeRequest)(nil), "portdomain.v1.GetPortInfoByCodeRequest")
	proto.RegisterType((*GetPortInfoByCodeResponse)(nil), "portdomain.v1.GetPortInfoByCodeResponse")
	proto.RegisterType((*GetPortInfoByCodeBatchRequest)(nil), "portdomain.v1.GetPortInfoByCodeBatchRequest")
	proto.RegisterType((*GetPortInfoByCodeBatchResponse)(nil), "portdomain.v1.GetPortInfoByCodeBatchResponse")
}

func init() {
	proto.RegisterFile("api/proto/portdomain/v1/port_domain_api.proto", fileDescriptor_91b0cf120d2396f8)
}

var fileDescriptor_91b0cf120d2396f8 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x55, 0xd2, 0x24, 0x6d, 0x26, 0xf4, 0x50, 0xb7, 0xaa, 0xcc, 0x22, 0x60, 0x9b, 0x0b, 0x7b,
	0xa0, 0xbb, 0x6a, 0x11, 0x1f, 0x40, 0x41, 0x42, 0x95, 0x7a, 0x28, 0x2b, 0x71, 0x8e, 0xcc, 0x66,
	0xb2, 0x58, 0xda, 0x78, 0x8c, 0xed, 0x44, 0x0a, 0x9f, 0xc6, 0x8d, 0x3f, 0x43, 0xb6, 0x77, 0x69,
	0x20, 0x2d, 0xe5, 0xe6, 0xf7, 0xe6, 0x3d, 0xcf, 0xbc, 0x91, 0x0d, 0xe7, 0x42, 0xcb, 0x42, 0x1b,
	0x72, 0x54, 0x68, 0x32, 0x6e, 0x4e, 0x4b, 0x21, 0x55, 0xb1, 0xbe, 0x08, 0x68, 0x16, 0xe1, 0x4c,
	0x68, 0x99, 0x07, 0x0d, 0x3b, 0xbc, 0x13, 0xe5, 0xeb, 0x8b, 0x84, 0xd7, 0x44, 0x75, 0x83, 0x85,
	0xdb, 0x68, 0x2c, 0x1a, 0xe1, 0x1a, 0x55, 0x47, 0xe1, 0xf4, 0x47, 0x1f, 0x06, 0xb7, 0x64, 0x1c,
	0x3b, 0x85, 0x51, 0x43, 0x15, 0xcd, 0x91, 0xf7, 0xd2, 0x5e, 0x36, 0x2e, 0x5b, 0xc4, 0x18, 0x0c,
	0x94, 0x58, 0x22, 0xef, 0x07, 0x36, 0x9c, 0x3d, 0x57, 0x49, 0xb7, 0xe1, 0x7b, 0x91, 0xf3, 0x67,
	0xc6, 0x61, 0xbf, 0xa2, 0x95, 0x72, 0x66, 0xc3, 0x07, 0x81, 0xee, 0x20, 0x3b, 0x81, 0xa1, 0x68,
	0xa4, 0xb0, 0x7c, 0x98, 0xee, 0x65, 0xe3, 0x32, 0x02, 0xaf, 0x37, 0x58, 0x4b, 0x52, 0x96, 0x8f,
	0x02, 0xdf, 0x41, 0xf6, 0x16, 0x26, 0x15, 0x91, 0x99, 0x4b, 0x25, 0x1c, 0x5a, 0xbe, 0x9f, 0xf6,
	0xb2, 0xc9, 0xe5, 0x71, 0x1e, 0x23, 0xe4, 0x3e, 0x42, 0x7e, 0x23, 0xdc, 0x8d, 0xaa, 0xcb, 0x6d,
	0x1d, 0x4b, 0xe0, 0x40, 0x1b, 0x5a, 0x4b, 0x55, 0x21, 0x3f, 0x08, 0x13, 0xfc, 0xc6, 0xbe, 0xe6,
	0xe4, 0x12, 0xbf, 0x93, 0x42, 0x3e, 0x8e, 0xb5, 0x0e, 0xfb, 0xe0, 0x2b, 0xd5, 0x50, 0x65, 0x39,
	0x84, 0x39, 0x5a, 0xc4, 0xce, 0xe0, 0xc9, 0x82, 0x0c, 0xca, 0x5a, 0xcd, 0xc2, 0x5a, 0x26, 0x69,
	0x2f, 0x1b, 0x96, 0x93, 0x96, 0x7b, 0x4f, 0x73, 0x9c, 0x1e, 0xc3, 0xd1, 0x67, 0x6d, 0xd1, 0x38,
	0xbf, 0xc1, 0x12, 0xbf, 0xad, 0xd0, 0xba, 0xe9, 0x09, 0xb0, 0x6d, 0xd2, 0x6a, 0x52, 0x16, 0xa7,
	0x09, 0xf0, 0x8f, 0x18, 0xa8, 0x6b, 0xb5, 0xa0, 0xab, 0x8d, 0xf7, 0x77, 0x8e, 0x67, 0xf0, 0xf4,
	0x9e, 0x5a, 0x6b, 0x7c, 0x09, 0xcf, 0x77, 0x8a, 0x57, 0xc2, 0x55, 0x5f, 0x3b, 0x77, 0x0a, 0x2f,
	0x1e, 0x12, 0xc4, 0x2b, 0x2e, 0x7f, 0xf6, 0xe1, 0xd0, 0xd7, 0x3f, 0x84, 0xf7, 0xf0, 0xee, 0xf6,
	0x9a, 0x7d, 0x02, 0xb8, 0x9b, 0x91, 0xa5, 0xf9, 0x1f, 0xaf, 0x25, 0xdf, 0xc9, 0x94, 0x9c, 0xfd,
	0x43, 0x11, 0x9b, 0xb0, 0x05, 0x1c, 0xed, 0x8c, 0xc1, 0x5e, 0xfd, 0xe5, 0x7b, 0x68, 0x05, 0x49,
	0xf6, 0xb8, 0xb0, 0xed, 0xb3, 0x82, 0xd3, 0xfb, 0xe3, 0xb2, 0xd7, 0x8f, 0xdd, 0xb1, 0xbd, 0xb6,
	0xe4, 0xfc, 0x3f, 0xd5, 0xb1, 0xed, 0x97, 0x51, 0xf8, 0x2e, 0x6f, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x46, 0xec, 0x00, 0x94, 0x88, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortDomainAPIClient is the client API for PortDomainAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortDomainAPIClient interface {
	UpsertPort(ctx context.Context, in *UpsertPortRequest, opts ...grpc.CallOption) (*UpsertPortResponse, error)
	GetPortInfoByCode(ctx context.Context, in *GetPortInfoByCodeRequest, opts ...grpc.CallOption) (*GetPortInfoByCodeResponse, error)
	GetPortInfoByCodeBatch(ctx context.Context, in *GetPortInfoByCodeBatchRequest, opts ...grpc.CallOption) (*GetPortInfoByCodeBatchResponse, error)
}

type portDomainAPIClient struct {
	cc *grpc.ClientConn
}

func NewPortDomainAPIClient(cc *grpc.ClientConn) PortDomainAPIClient {
	return &portDomainAPIClient{cc}
}

func (c *portDomainAPIClient) UpsertPort(ctx context.Context, in *UpsertPortRequest, opts ...grpc.CallOption) (*UpsertPortResponse, error) {
	out := new(UpsertPortResponse)
	err := c.cc.Invoke(ctx, "/portdomain.v1.PortDomainAPI/UpsertPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portDomainAPIClient) GetPortInfoByCode(ctx context.Context, in *GetPortInfoByCodeRequest, opts ...grpc.CallOption) (*GetPortInfoByCodeResponse, error) {
	out := new(GetPortInfoByCodeResponse)
	err := c.cc.Invoke(ctx, "/portdomain.v1.PortDomainAPI/GetPortInfoByCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portDomainAPIClient) GetPortInfoByCodeBatch(ctx context.Context, in *GetPortInfoByCodeBatchRequest, opts ...grpc.CallOption) (*GetPortInfoByCodeBatchResponse, error) {
	out := new(GetPortInfoByCodeBatchResponse)
	err := c.cc.Invoke(ctx, "/portdomain.v1.PortDomainAPI/GetPortInfoByCodeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortDomainAPIServer is the server API for PortDomainAPI service.
type PortDomainAPIServer interface {
	UpsertPort(context.Context, *UpsertPortRequest) (*UpsertPortResponse, error)
	GetPortInfoByCode(context.Context, *GetPortInfoByCodeRequest) (*GetPortInfoByCodeResponse, error)
	GetPortInfoByCodeBatch(context.Context, *GetPortInfoByCodeBatchRequest) (*GetPortInfoByCodeBatchResponse, error)
}

// UnimplementedPortDomainAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPortDomainAPIServer struct {
}

func (*UnimplementedPortDomainAPIServer) UpsertPort(ctx context.Context, req *UpsertPortRequest) (*UpsertPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPort not implemented")
}
func (*UnimplementedPortDomainAPIServer) GetPortInfoByCode(ctx context.Context, req *GetPortInfoByCodeRequest) (*GetPortInfoByCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortInfoByCode not implemented")
}
func (*UnimplementedPortDomainAPIServer) GetPortInfoByCodeBatch(ctx context.Context, req *GetPortInfoByCodeBatchRequest) (*GetPortInfoByCodeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortInfoByCodeBatch not implemented")
}

func RegisterPortDomainAPIServer(s *grpc.Server, srv PortDomainAPIServer) {
	s.RegisterService(&_PortDomainAPI_serviceDesc, srv)
}

func _PortDomainAPI_UpsertPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainAPIServer).UpsertPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portdomain.v1.PortDomainAPI/UpsertPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainAPIServer).UpsertPort(ctx, req.(*UpsertPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortDomainAPI_GetPortInfoByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortInfoByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainAPIServer).GetPortInfoByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portdomain.v1.PortDomainAPI/GetPortInfoByCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainAPIServer).GetPortInfoByCode(ctx, req.(*GetPortInfoByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortDomainAPI_GetPortInfoByCodeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortInfoByCodeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainAPIServer).GetPortInfoByCodeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portdomain.v1.PortDomainAPI/GetPortInfoByCodeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainAPIServer).GetPortInfoByCodeBatch(ctx, req.(*GetPortInfoByCodeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortDomainAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portdomain.v1.PortDomainAPI",
	HandlerType: (*PortDomainAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertPort",
			Handler:    _PortDomainAPI_UpsertPort_Handler,
		},
		{
			MethodName: "GetPortInfoByCode",
			Handler:    _PortDomainAPI_GetPortInfoByCode_Handler,
		},
		{
			MethodName: "GetPortInfoByCodeBatch",
			Handler:    _PortDomainAPI_GetPortInfoByCodeBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/portdomain/v1/port_domain_api.proto",
}
