// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/portdomain/v1/port_info.proto

package portdomainv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	Locode               string         `protobuf:"bytes,1,opt,name=locode,proto3" json:"locode,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string         `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string         `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string       `protobuf:"bytes,5,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string       `protobuf:"bytes,6,rep,name=regions,proto3" json:"regions,omitempty"`
	Coordinates          *latlng.LatLng `protobuf:"bytes,7,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Province             string         `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Timezone             string         `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string       `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	ForeignCode          int32          `protobuf:"varint,11,opt,name=foreign_code,json=foreignCode,proto3" json:"foreign_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a18d5d151af889, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetLocode() string {
	if m != nil {
		return m.Locode
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() *latlng.LatLng {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetForeignCode() int32 {
	if m != nil {
		return m.ForeignCode
	}
	return 0
}

func init() {
	proto.RegisterType((*Port)(nil), "portdomain.v1.Port")
}

func init() {
	proto.RegisterFile("api/proto/portdomain/v1/port_info.proto", fileDescriptor_06a18d5d151af889)
}

var fileDescriptor_06a18d5d151af889 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x95, 0xfe, 0xaf, 0xd3, 0xf7, 0x1d, 0x0c, 0x42, 0xa7, 0x4e, 0x81, 0x85, 0x4c, 0x89,
	0x0a, 0xe2, 0x0b, 0xc0, 0xda, 0x01, 0x65, 0x64, 0xa9, 0x8c, 0xe3, 0x5a, 0x96, 0xdc, 0xbb, 0xc8,
	0x71, 0x23, 0x95, 0x8f, 0xc6, 0xa7, 0x43, 0x76, 0x12, 0xca, 0x76, 0xbf, 0xdf, 0x73, 0xc3, 0xdd,
	0xc3, 0x1e, 0x45, 0x63, 0xca, 0xc6, 0x91, 0xa7, 0xb2, 0x21, 0xe7, 0x6b, 0x3a, 0x09, 0x83, 0x65,
	0xb7, 0x8b, 0x74, 0x30, 0x78, 0xa4, 0x22, 0xa6, 0xfc, 0xdf, 0x35, 0x2e, 0xba, 0xdd, 0x16, 0x34,
	0x91, 0xb6, 0xaa, 0xf4, 0x97, 0x46, 0x95, 0x56, 0x78, 0x8b, 0xba, 0x5f, 0x7c, 0xf8, 0x9e, 0xb0,
	0xd9, 0x3b, 0x39, 0xcf, 0xef, 0xd8, 0xc2, 0x92, 0xa4, 0x5a, 0x41, 0x92, 0x25, 0xf9, 0xba, 0x1a,
	0x88, 0x73, 0x36, 0x43, 0x71, 0x52, 0x30, 0x89, 0x36, 0xce, 0xc1, 0x49, 0xe3, 0x2f, 0x30, 0xed,
	0x5d, 0x98, 0x39, 0xb0, 0xa5, 0xa4, 0x33, 0x7a, 0x77, 0x81, 0x59, 0xd4, 0x23, 0xf2, 0x5b, 0x36,
	0x17, 0xd6, 0x88, 0x16, 0xe6, 0xd9, 0x34, 0x5f, 0x57, 0x3d, 0x84, 0x7d, 0xa7, 0xb4, 0x21, 0x6c,
	0x61, 0x11, 0xfd, 0x88, 0xfc, 0x85, 0xa5, 0x92, 0xc8, 0xd5, 0x06, 0x85, 0x57, 0x2d, 0x2c, 0xb3,
	0x24, 0x4f, 0x9f, 0x6e, 0x8a, 0xfe, 0x85, 0x22, 0xbc, 0x50, 0xec, 0x85, 0xdf, 0xa3, 0xae, 0xfe,
	0xee, 0xf1, 0x2d, 0x5b, 0x35, 0x8e, 0x3a, 0x83, 0x52, 0xc1, 0x2a, 0x5e, 0xf0, 0xcb, 0x21, 0xf3,
	0xe6, 0xa4, 0xbe, 0x08, 0x15, 0xac, 0xfb, 0x6c, 0xe4, 0xf0, 0xf8, 0x19, 0x2d, 0xc9, 0x16, 0x58,
	0xbc, 0x63, 0x20, 0x7e, 0xcf, 0x36, 0x47, 0x72, 0xca, 0x68, 0x3c, 0xc4, 0x5a, 0xd2, 0x2c, 0xc9,
	0xe7, 0x55, 0x3a, 0xb8, 0x37, 0xaa, 0xd5, 0xeb, 0xff, 0x8f, 0xcd, 0xb5, 0xe7, 0x6e, 0xf7, 0xb9,
	0x88, 0x9d, 0x3e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x6e, 0x3f, 0x0f, 0xa7, 0x01, 0x00,
	0x00,
}
