version: '3.1'

services:

  postgres:
    image: postgis/postgis
    container_name: portdomain-db
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  portdomain:
    image: "getupandgo/portdomain:0.1"
    environment:
      - CONFIG_PATH=/config/config.yaml
    container_name: portdomain
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "9000:9000"

  api:
    image: "getupandgo/clientapi:0.1"
    environment:
        - CONFIG_PATH=/config/config.yaml
    container_name: clientapi
    depends_on:
      - portdomain
    restart: on-failure
    ports:
      - "8000:8000"